/**
 * @file useRecurring.js
 * @description Custom React hook for all recurring transaction rule API operations.
 * Mirrors the pattern of useTransactions.js for consistency.
 */

import { useState, useCallback } from 'react';
import api from '../api/axiosInstance';
import toast from 'react-hot-toast';
import { getLocalStorageCache, setLocalStorageCache } from '../utils/cacheManager';

export const useRecurring = () => {
  const [rules, setRules] = useState([]);
  const [upcoming, setUpcoming] = useState([]);
  const [upcomingSummary, setUpcomingSummary] = useState({ totalIncome: 0, totalExpense: 0 });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // 1. Fetch all recurring rules for the logged-in user
  const fetchRules = useCallback(async (options = {}) => {
    const cachedRules = getLocalStorageCache('recurring_rules');
    if (cachedRules && !options.skipCache) {
      setRules(cachedRules);
      setLoading(false);
    } else {
      setLoading(true);
    }

    setError(null);
    try {
      const res = await api.get('/recurring', options);
      setRules(res.data.data);
      setLocalStorageCache('recurring_rules', res.data.data);
    } catch (err) {
      if (!cachedRules) {
        const msg = err.response?.data?.message || 'Failed to fetch recurring rules';
        setError(msg);
        toast.error(msg);
      }
    } finally {
      setLoading(false);
    }
  }, []);

  // 2. Fetch upcoming recurring transactions for the next 30 days (Dashboard)
  const fetchUpcoming = useCallback(async () => {
    const cachedUpcoming = getLocalStorageCache('recurring_upcoming');
    if (cachedUpcoming) {
      setUpcoming(cachedUpcoming.data || []);
      setUpcomingSummary(cachedUpcoming.summary || { totalIncome: 0, totalExpense: 0 });
    }

    try {
      const res = await api.get('/recurring/upcoming');
      setUpcoming(res.data.data);
      setUpcomingSummary(res.data.summary);
      setLocalStorageCache('recurring_upcoming', { data: res.data.data, summary: res.data.summary });
    } catch (err) {
      console.error('Failed to load upcoming recurring transactions:', err.message);
    }
  }, []);

  // 3. Create a new recurring rule
  const createRule = async (ruleData) => {
    setLoading(true);
    try {
      const res = await api.post('/recurring', ruleData);
      toast.success(res.data.message || 'Recurring rule created!');
      setRules((prev) => [res.data.data, ...prev]);
      return res.data.data;
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to create recurring rule';
      toast.error(msg);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  // 4. Update an existing recurring rule
  const updateRule = async (id, ruleData) => {
    setLoading(true);
    try {
      const res = await api.put(`/recurring/${id}`, ruleData);
      toast.success(res.data.message || 'Recurring rule updated!');
      setRules((prev) => prev.map((r) => (r._id === id ? res.data.data : r)));
      return res.data.data;
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to update recurring rule';
      toast.error(msg);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  // 5. Delete a recurring rule (preserves generated transactions)
  const deleteRule = async (id) => {
    setLoading(true);
    try {
      const res = await api.delete(`/recurring/${id}`);
      toast.success(res.data.message || 'Recurring rule deleted');
      setRules((prev) => prev.filter((r) => r._id !== id));
      return true;
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to delete recurring rule';
      toast.error(msg);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  // 6. Toggle a rule active/paused
  const toggleRule = async (id) => {
    try {
      const res = await api.patch(`/recurring/${id}/toggle`);
      toast.success(res.data.message || 'Status updated');
      setRules((prev) => prev.map((r) => (r._id === id ? res.data.data : r)));
      return res.data.data;
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to toggle rule';
      toast.error(msg);
      throw err;
    }
  };

  // 7. Fetch transaction history generated by a specific rule
  const fetchHistory = async (id) => {
    try {
      const res = await api.get(`/recurring/${id}/history`);
      return res.data.data;
    } catch (err) {
      const msg = err.response?.data?.message || 'Failed to load history';
      toast.error(msg);
      return [];
    }
  };

  return {
    rules,
    upcoming,
    upcomingSummary,
    loading,
    error,
    fetchRules,
    fetchUpcoming,
    createRule,
    updateRule,
    deleteRule,
    toggleRule,
    fetchHistory,
  };
};

export default useRecurring;
